### ISSUE TITLE
Error in configuration file

### ISSUE THREAD

**Issue by aslozada** [grimme-lab/nlopt-f#7]
@awvwgk,

this error appears with cmake:

``
CMake Error at CMakeLists.txt:33 (math):
  math cannot parse the expression: " * 10000

    + * 100
    +": syntax error, unexpected exp_TIMES (2).

--
cmake version 3.16.3
ninja version 1.10.0
Fortran compiler 9.3.0

**Comment by awvwgk** [comment]
Can you share which version of NLopt you are using? Does this one come with a CMake config file?

**Comment by aslozada** [comment]
> Can you share which version of NLopt you are using? Does this one come with a CMake config file?

@awvwgk ,
I forgot that information in the previous comment
`nlopt version 2.6.2`

I am now checking if it is a localization problem of the `nlopt` libraries.

---
I find the description of the proposal interesting, will your tblite library be embedded in `xtb`?

**Comment by awvwgk** [comment]
This error would happen if CMake can find NLopt

https://github.com/grimme-lab/nlopt-f/blob/37a418f0f0f96c7ca109ce8083454327bc197068/CMakeLists.txt#L29-L31

but the config file does not set the `NLopt_VERSION_*` variables as promised by the [CMake documentation](https://cmake.org/cmake/help/v3.16/command/find_package.html#version-selection).

Not sure how I should solve this, one option would write a custom finder which can guarantee that the variables are set. This might be preferable because than we can also use pkg-config to find older NLopt versions build with autotools.

Or CMake didn't find NLopt because I forgot to add the `REQUIRED` to the finder. Could you attach the full configuration output?

---

Yes, this is the ultimate plan for the *tblite* library, to provide one place for a reference implementation of the xTB Hamiltonian, which is usable for everybody who doesn't want to implement the Hamiltonians themselves. Using it in `xtb` is planned for version 6.5.0, but I have no concrete time when this will happen.

**Comment by aslozada** [comment]
> Or CMake didn't find NLopt because I forgot to add the `REQUIRED` to the finder

Now nlopt-f installation via CMake is ok.

--
I tried some simple examples for configuration files, CMakeList, but an error for locating the libraries persists. 
Maybe I forgot something

`  Target "main" links to target "nlopt-f::nlopt::wrap" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?`
[CMakeLists.txt](https://github.com/grimme-lab/nlopt-f/files/6989064/CMakeLists.txt)

**Comment by awvwgk** [comment]
Sorry, I thought you were seeing an error when building NLopt rather than building a project against the wrapper. This is a typo in the README, it should use the target `nlopt-f::nlopt-f` instead. Will fix this in #8.

For finding the project robustly downstream I recommend to use a find module. You can adapt the one for test-drive here and have your project add it to the `CMAKE_MODULE_PATH`:
https://github.com/grimme-lab/nlopt-f/blob/main/config/cmake/Findtest-drive.cmake
I don't include it in the README because it is a lot of CMake boilerplate code.

**Comment by aslozada** [comment]
> This is a typo in the README, it should use the target `nlopt-f::nlopt-f` instead. Will fix this in #8.

For my simple configuration file, CMakeLists.txt, #8 works!

--
I will use a find module

**Comment by awvwgk** [comment]
Thanks for testing. Getting CMake projects working as dependencies is... tricky.

Will close this as resolved.
